In [1]:
#Khởi tạo ngay từ đầu

#int
import numpy as np
A = np.array([[1,2],
             [3,4]])

print(A)
print("dtype of matrix A:", A.dtype)


#float

B = np.array([[1,2],
            [3,4]], dtype = np.float)
print(B)
print('type of matrix B:', B.dtype)

[[1 2]
 [3 4]]
dtype of matrix A: int32
[[1. 2.]
 [3. 4.]]
type of matrix B: float64


In [2]:
#Ngoài cách thay đổi trên, định dạng của ma trận cũng có thể được biến đổi thông qua hàm A.astype().
#Đây là một hàm thuộc tính có sẵn ở mỗi mảng.

A = A.astype(np.float32)
print(A.dtype)

float32


In [3]:
#Khởi tạo ngẫu nhiên

R = np.random.randn(2,3)
print(R)

[[ 0.56534797  0.59557002  0.21971696]
 [ 1.14462703 -1.72305337 -1.28290879]]


In [4]:
# khoi tao Gaussian distribution

R = np.random.normal(loc = 1, scale = 2, size = (2,3))
R
# trung bình chính là loc
# phương sai là scale

array([[-0.17848808,  0.93023787,  3.73902155],
       [-0.64094988,  0.76215568,  1.16284118]])

In [5]:
#np.random.uniform(low=0.0, high=1.0, size=None)
#Các phần tử sẽ được khởi tạo theo phân phối đều trong khoảng từ low -> hight

In [6]:
R = np.random.uniform(low=-1, high=1, size=(2, 3))
print(R)

[[-0.82900933 -0.28521114  0.38875745]
 [-0.17362453  0.48790364  0.2370422 ]]


In [7]:
#Trong trường hợp bạn chỉ muốn sinh ngẫu nhiên đối với số nguyên thì có thể sử dụng hàm np.randint()
R = np.random.randint(low=-5, high=5, size=(2, 3))
print(R)

[[ 3  4 -3]
 [-2  0 -4]]


In [8]:








#Đọc và save numpy từ file

In [9]:
import numpy as np

# Khởi tạo một mảng ngẫu nhiên A
A = np.random.randn(3, 3)
A

array([[-1.47334681,  0.64373172, -0.92774032],
       [ 1.09270285,  0.5169213 ,  0.07216077],
       [ 1.23105255, -1.77044164,  0.50784237]])

In [10]:
#  np.save(file, arr): Output là định dạng npy. Save được mọi tensor với số chiều tuỳ ý.
#np.savetxt(file, arr): Output là định dạng txt. Cách này ít phổ biến hơn vì ta chỉ save được mảng 1D và 2D

# Định dạng npy
np.save('A', A)
# Định dạng txt
np.savetxt('A.txt', A)

In [11]:
# Load numpy từ file
A = np.load('A.npy')
print(A)

[[-1.47334681  0.64373172 -0.92774032]
 [ 1.09270285  0.5169213   0.07216077]
 [ 1.23105255 -1.77044164  0.50784237]]


In [12]:
A = np.loadtxt('A.txt')
print(A)

[[-1.47334681  0.64373172 -0.92774032]
 [ 1.09270285  0.5169213   0.07216077]
 [ 1.23105255 -1.77044164  0.50784237]]


In [13]:
#convert mảng từ dataframe


In [14]:
import pandas as pd
df = pd.read_csv("A.txt", header=None, sep=" ")
df

0         1         2
0 -1.473347  0.643732 -0.927740
1  1.092703  0.516921  0.072161
2  1.231053 -1.770442  0.507842

In [15]:
A = df.values
print(A)

[[-1.47334681  0.64373172 -0.92774032]
 [ 1.09270285  0.5169213   0.07216077]
 [ 1.23105255 -1.77044164  0.50784237]]


In [16]:
#Thay đổi shape của mảng





In [17]:
B = np.array(np.arange(12))
print("B: \n", B)
print("B.shape: ", B.shape)

B: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
B.shape:  (12,)


In [18]:
B.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [19]:
np.reshape(B,(2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [20]:
#Trong một mảng có n chiều, khi đã biết n−1 chiều thì chiều còn lại có thể tính ra được bằng cách chia tổng số phần tử cho tích của n−1 chiều.
#Do đó chúng ta có thể đánh dấu chiều chưa biết bằng -1 để numpy sẽ tự tính.

B.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [21]:



#Chuyển vị các chiều

#batch_size x width x height x channels   (tensorflow)
#batch_size x channels x width x height (pytorch)

In [22]:
A = np.random.randint(0,255, size = (3,28,28))
print("A.shape", A.shape)

A.shape (3, 28, 28)


In [23]:
A = np.transpose(A,(1,2,0))
A.shape

(28, 28, 3)

In [24]:
#Concatenate và Stack hai mảng

#Giả sử bạn đang có rất nhiều bức ảnh khác nhau.
#Bạn muốn ghép các bức ảnh đó theo chiều height (một bức nằm trái và một bức nằm phải). 
#Để thực hiện được điều này thì bạn cần tới câu lệnh concatenate.






    

In [25]:
A = np.random.randint(0,255, size = (28,28,3))
B = np.random.randint(0,255, size = (28,28,3))

print(A.shape)
print(B.shape)

AB = np.concatenate((A,B),axis = 1)
print(AB.shape)

(28, 28, 3)
(28, 28, 3)
(28, 56, 3)


In [26]:
#Ngoài ra muốn tạo một batch cho huấn luyện,
#trong batch đó gồm 2 ảnh là A và B thì chúng ta sử dụng câu lệnh stack.

np.stack([A,B]).shape

(2, 28, 28, 3)

In [27]:
# Stack theo chiều vertical
print(np.vstack([A, B]).shape)

# Stack theo chiều horizontal
print(np.hstack([A, B]).shape)

(56, 28, 3)
(28, 56, 3)


In [28]:
#Mở rộng mảng




In [29]:
A = np.random.randint(0, 2, size=(1, 2, 3))
B = np.random.randint(0, 2, size=(1, 3))


In [30]:
# Mở rộng mảng
B = np.expand_dims(B, axis=-1)
print("B new shape: ", B.shape)
print("A.dot(B) shape: ", A.dot(B).shape)

B new shape:  (1, 3, 1)
A.dot(B) shape:  (1, 2, 1, 1)


In [31]:
#Đối số axis=-1 có nghĩa là ta sẽ mở rộng mảng tại chiều cuối cùng

In [32]:
#Các hàm trên numpy


B = np.array([[ 0,  1,  2,  3,  4,  5],
              [ 6,  7,  8,  9, 10, 11]])

In [33]:
# Tìm ra phần tử nhỏ nhất của B theo cột
B.min(axis=1)

array([0, 6])

In [34]:
# Tìm ra phần tử nhỏ nhất của B theo hàng
B.min(axis=0)

array([0, 1, 2, 3, 4, 5])

In [35]:
print(B.max(axis=1))
print(B.mean(axis=1))
print(B.sum(axis=1))

[ 5 11]
[2.5 8.5]
[15 51]


In [36]:
#minimum, maximum

A = np.array([[1, 3, 6], 
              [2, 7, 9]])

B = np.array([[0, 4, 5], 
              [1, 6, 10]])

# Tìm các phần tử maximum của A và B ở cùng vị trí indice
np.maximum(A, B)

array([[ 1,  4,  6],
       [ 2,  7, 10]])

In [37]:
#argmax, argmin

A = np.array([1, 5, 3, 2, 4])
np.argmax(A)

1

In [38]:
# Tìm ra indice có giá trị lớn nhất của các dòng
A = np.array([[1, 2],
              [3, 4],
              [5, 0],
              [2, 1]])

np.argmax(A, axis=1)

array([1, 1, 0, 0], dtype=int64)

In [39]:
#argsort
#Hàm argsort là hàm tìm ra indices được sắp xếp theo số thứ tự tăng dần của một mảng hoặc một véc tơ.
B = np.array([[0.1, 0.2, 0.7],
              [0.6, 0.4, 0.0],
              [0.1, 0.5, 0.4],
              [0.3, 0.3, 0.4],
              [0.1, 0.8, 0.1]])

In [40]:
np.argsort(B, axis = 0)

array([[0, 0, 1],
       [2, 3, 4],
       [4, 1, 2],
       [3, 2, 3],
       [1, 4, 0]], dtype=int64)

In [41]:
# Tìm ra indice của các dòng theo thứ tự tăng dần

np.argsort(B, axis = 1)

array([[0, 1, 2],
       [2, 1, 0],
       [0, 2, 1],
       [0, 1, 2],
       [0, 2, 1]], dtype=int64)

In [42]:
#np.exp() và hàm softmax





np.exp(B)

array([[1.10517092, 1.22140276, 2.01375271],
       [1.8221188 , 1.4918247 , 1.        ],
       [1.10517092, 1.64872127, 1.4918247 ],
       [1.34985881, 1.34985881, 1.4918247 ],
       [1.10517092, 2.22554093, 1.10517092]])

In [43]:
E = np.exp(B)
P = []

for i in range(E.shape[0]):
    Ei = E[i,:]
    pi = Ei/np.sum(Ei)
    P.append(pi)
    
P = np.array(P)
P

array([[0.25462853, 0.28140804, 0.46396343],
       [0.42237892, 0.34581461, 0.23180647],
       [0.26030255, 0.38832577, 0.35137169],
       [0.32204346, 0.32204346, 0.35591307],
       [0.2491434 , 0.5017132 , 0.2491434 ]])

In [45]:
#Giữ nguyên shape

np.max(B, axis = 1)

array([0.7, 0.6, 0.5, 0.4, 0.8])

In [46]:
#Khi sử dụng keepdims=True thì kết quả trả ra sẽ là một ma trận,
#chiều bị tiêu giảm sẽ được thay thế bởi kích thước 1.

np.max(B, axis = 1, keepdims=True)

array([[0.7],
       [0.6],
       [0.5],
       [0.4],
       [0.8]])

In [47]:
# seed in python
# giữ nguyên các giá trị khởi tạo

import numpy as np
np.random.seed(123)
np.random.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [48]:
np.random.seed(123)
np.random.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [ ]:
#Các ma trận đặc biệt



In [49]:
# Khởi tạo ma trận đơn vị với shape=5x5
I = np.identity(5, dtype=np.float16)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float16)

In [50]:
# Khởi tạo ma trận 1 với kích thước (3, 3)
A = np.ones((3, 3), dtype=np.float32)
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [51]:
# Khởi tạo ma trận B ngẫu nhiên kích thước (2, 3)
B = np.random.randn(2,3)
# Khởi tạo ma trân 1 có kích thước bằng với (2, 3)
A = np.ones_like(B)
A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [52]:
# Khởi tạo ma trận 0 kích thước (3, 3)
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
# Khởi tạo ma trận 0 có kích thước như ma trận B
np.zeros_like(B)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
np.diag(np.array([1, 2, 3]))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [55]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8 ,9]])

# Đường chéo chính của ma trận A
np.diag(A)

array([1, 5, 9])

In [ ]:
#Các phép toán trên ma trận



In [56]:
print("Original matrix: \n", A)
print("Transpose matrix: \n", A.T)

Original matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose matrix: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [57]:
#Ma trận nghịch đảo
# Tính ma trận nghịch đảo của A
# pinv là pseudo-inverse of a matrix

A = np.array([[1, 2.5, 2],
              [3, 4.2, 1],
              [5, 2.1, 2]])

A_inv=np.linalg.pinv(A)

print("Inverse A: ")
A_inv

Inverse A: 


array([[-0.24609375,  0.03125   ,  0.23046875],
       [ 0.0390625 ,  0.3125    , -0.1953125 ],
       [ 0.57421875, -0.40625   ,  0.12890625]])

In [58]:
#Tích của ma trận A với ma trận nghịch đảo của nó là một ma trận đơn vị.
A.dot(A_inv)

array([[ 1.00000000e+00,  4.44089210e-16, -6.10622664e-16],
       [ 2.22044605e-16,  1.00000000e+00, -6.10622664e-16],
       [-2.22044605e-16, -4.44089210e-16,  1.00000000e+00]])

In [ ]:
#Hạng (rank) của ma trận



#Hệ véc tơ độc lập tuyến tính là gì?
#Một hệ véc tơ e1,e2,…,en là độc lập tuyến tính nếu phương trình:
#k1e1+k2e2+⋯+knen=0
#có một nghiệm duy nhất k1=k2=⋯=kn=0

#Trái lại, nếu tồn tại một nghiệm mà kj≠0 thì hệ véc tơ là phụ thuộc tuyến tính.

#Một hệ véc tơ độc lập truyến tính thì tạo ra một không gian véc tơ. 
#Khi đó mọi véc tơ khác có thể được biểu diễn dưới dạng tổ hợp tuyến tính của những véc tơ này.

In [ ]:
#Hạng của ma trận là gì?
#Hạng của ma trận là số lượng các chiều trong không gian véc tơ được sinh ra bởi các cột (hoặc dòng) của ma trận A. 
#Nó chính bằng số lượng lớn nhất các cột (hoặc dòng) độc lập truyến tính của ma trận A.

In [59]:
np.linalg.matrix_rank(A)

3

In [60]:
#Định thức


# Tính định thức của A
np.linalg.det(A)

-25.6

In [61]:
#Trace của một ma trận là tổng của các phần tử nằm trên đường chéo chính.

print("matrix A: \n", A)
print("trace of A: ", np.trace(A))

matrix A: 
 [[1.  2.5 2. ]
 [3.  4.2 1. ]
 [5.  2.1 2. ]]
trace of A:  7.2


In [ ]:
#Chuẩn Frobenious
#||AF||=∑i=1m∑j=1na2ij
#Tương tự như chuẩn L2 đối với véc tơ.
#Chuấn Frobenious của một ma trận bằng căn bậc hai của tổng bình phương các thành phần trong ma trận đó
np.linalg.norm(A, ord='fro')

In [ ]:

#Các phép cộng, trừ

In [62]:
import numpy as np
A = np.array([[1, 4, 2],
              [3, 2, 1],
              [4, 6, 7]])

B = np.array([[0, 3, 4],
              [3, 4, 2],
              [4, 6, 8]])

A - B

array([[ 1,  1, -2],
       [ 0, -2, -1],
       [ 0,  0, -1]])

In [ ]:
#Phép nhân ma trận thông thường

In [63]:
import numpy as np
A = np.array([[1, 4, 2],
              [3, 2, 1]])

B = np.array([[0, 3],
              [3, 4],
              [4, 6]])

np.dot(A, B)
# Hoặc
A.dot(B)
# Hoặc
A@B

array([[20, 31],
       [10, 23]])

In [ ]:
#Tích Hadamard (element-wise product) giữa hai ma trận

In [ ]:
#Tích Hadamard giữa hai ma trận A và B có cùng kích thước là một ma trận có cùng kích thước với A và B.
#Khi đó mỗi một phần tử của ma trận bằng tích của các phần tử ở cùng vị trí.

In [64]:
C = np.array([[2, 1, 2],
              [1, 0, 1]])

D = np.array([[0, 2, 4],
              [2, 3, 1]])

C*D

array([[0, 2, 8],
       [2, 0, 1]])

In [65]:
#Nhân ma trận với một véc tơ

x = np.array([1, 2, 3])
A.dot(x)




array([15, 10])

In [ ]:
#Nhân ma trận với một scaler

In [67]:
#Khi nhân ma trận với một scaler chúng ta lấy từng phần tử của ma trận đó nhân với scaler.
print(A)
A*5

[[1 4 2]
 [3 2 1]]


array([[ 5, 20, 10],
       [15, 10,  5]])

In [68]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 5])
# Phép cộng
a+b
# Tích vô hướng
a.dot(b)
# Tích có hướng
a*b
# cosine similarity
a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b))

0.954029957691665

In [69]:
# Hoặc cách khác để tính cosine similarity
from sklearn.metrics.pairwise import cosine_similarity
a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 5]])

cosine_similarity(a, b)

array([[0.95402996]])

In [70]:
#Thành phần của mảng
print('shape: ', A.shape)
print('number dims: ', A.ndim)
print('dtype: ', A.dtype)
print('item bytes size: ', A.itemsize)
print('bytes size: ', A.nbytes)

shape:  (2, 3)
number dims:  2
dtype:  int32
item bytes size:  4
bytes size:  24


In [71]:
A.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False